### PR TITLE
Fix error handling

### LINKED ISSUE #1014: Catch errors
Seems like #1002

Trying to create a client, when swagger.json can't be loaded:

```
Swagger('/not.exist.api/swagger.json')
  .then((client) => {
    console.log('client', client);
  })
  .catch((error) => {
    console.log('error', error);
  });
```

But instead of catch 404 error, you get an client with spec like this
`
["H",
"T",
"T",
"P",
" ",
"4",
"0",
"4",
" ",
"N",
"o",
"t",
" ",
"F",
"o",
"u",
"n",
"d"]
`

### PR DESCRIPTION
**Pull request by buunguyen**
This fixes #1014 and #1002.

@fehguy please take a look. One thing of note: because fetch is shared for both spec loading & operation execution, the change affects operations, see https://github.com/swagger-api/swagger-js/compare/master...buunguyen:fix-error-handling-2?expand=1#diff-7e3bd8e7059a21bfd255649cbfc84b33R130 (must change from `then` to `catch`). This can be considered a breaking change from semver perspective. UI/editor might need to change.

### CODE REVIEW

File: src/resolver.js [hunk 1]
```diff
@@ -30,29 +32,29 @@ export default function resolve({http, fetch, spec, url, baseDoc, mode, allowMet
...
-    plugins: plugs,
-    allowMetaPatches // allows adding .meta patches, which include adding `$$ref`s to the spec
-  }).then(normalizeSwagger)
+    const plugs = [plugins.refs]
+
+    if (mode !== 'strict') {
+      plugs.push(plugins.allOf)
+    }
+
+    // mapSpec is where the hard work happens, see https://github.com/swagger-api/specmap for more details
```
Comment (webron) [inline src/resolver.js]: Hmm... not anymore ;)

**Comment by buunguyen** [comment]
@webron this is technically breaking change of a corner case. Given we just release, should we ignore semver rule?

**Comment by webron** [comment]
@buunguyen I think so. Based on our chat, we might introduce additional such changes. Until we stabilize it more, it's ok. We should note that well in the release notes though.
