### PR TITLE
Encode form data according to Encoding Object

### LINKED ISSUE #1470: Encoding style not respected for requestBody
### Q&A (please complete the following information)
 - OS: Arch Linux
 - Environment: Firefox 68
 - Method of installation: swagger-editor
 - Swagger-Client version: 3.9.4
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
openapi: "3.0.2"
info:
  version: "1.0.0"
  title: "Swagger Petstore"
servers:
  - url: "https://petstore.swagger.io/"
paths:
  /pet:
    post:
      tags:
      - "pet"
      summary: "Add a new pet to the store"
      description: ""
      operationId: "addPet"
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                list:
                  type: array
                  items:
                    type: string
                hashmap:
                  # complex types are stringified to support RFC 1866
                  type: object
                  properties:
                    foo:
                      type: string
                    bar:
                      type: integer
            encoding:
              list:
                style: spaceDelimited
                explode: false
              hashmap:
                style: deepObject
                explode: true
                  
      responses:
        default:
          description: 'Nothing to see here'
```

Swagger-Client usage:
```js
// Run via swagger-editor
```

### Describe the bug you're encountering
swagger-client does not respect encoding style for complex parameters when inside `requestBody`. [As per the OpenAPI 3.0 specification][2], complex parameter encoding should follow the `encoding` parameter and work pretty much the same way as query parameter encoding.

### To reproduce...
When submitting a POST request via `addPet` with the following content:

```json
{
    "id": 1,
    "list": ["a", "b,c"],
    "hashmap": {"foo": "string", "bar": 0}
}
```

...a request with the following body is sent:

```
id=1&list=a%2Cb%2Cc&hashmap=%7B%0A%20%20%22foo%22%3A%20%22string%22%2C%0A%20%20%22bar%22%3A%200%0A%7D
```

[This corresponds to `hashmap` being json-encoded and `list` in a comma-separated format][1]. No further escaping of the contents will be performed, so if any of the elements in `list` contain commas, those will be indistinguisable from the element separators. This is despite the `encoding` field specifying that `list` should be space-delimited and that `hashmap` should be rendered as a deep-object.

### Expected behavior
For the example given above, the correct serialization method should result in this being sent as the request body:

```
id=1&list=a%20b%2Cc&hashmap[foo]=string&hashmap[bar]=0
```

[1]: https://github.com/swagger-api/swagger-js/blob/f8fccb45107c76c0dd45d9d0e4583087b97ef6b3/src/execute/oas3/build-request.js#L74-L81
[2]: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#encoding-object

### PR DESCRIPTION
**Pull request by abcang**
### Description

Serialize value with respect to `Encoding Object` when the content-type of the request body is `application/x-www-form-urlencoded`.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#encoding-object

Also, OpenAPI v3.1 has a specification to serialize similarly when content-type is `multipart/form-data`, so it was implemented at the same time.
https://github.com/OAI/OpenAPI-Specification/blob/v3.1.0-dev/versions/3.1.0.md#encodingObject

In addition, a bug that prevented sending an array of files was also fixed.

### Motivation and Context

Currently, swagger-client does not work according to the serialization specification of the request body of the form. This pull request is modified to respect the request body serialization settings.
In OpenAPI v3.1, the serialization settings will be respected even when the content-type is `multipart/form-data`. Although the specification has not yet been officially released, I implemented it before release because I felt it was practical.

Fixes #1470

### How Has This Been Tested?

I connected it to swagger-ui and did a simple operation check. Test cases have been added for important cases.

### Types of changes

- [ ] No code changes (changes to documentation, CI, metadata, etc)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/execute/oas3/parameter-builders.js [hunk 1]
```diff
@@ -46,58 +47,9 @@ export function query({req, value, parameter}) {
...
-        value: stylize({
-          key: encodedParamName,
-          value,
-          style: parameter.style || 'form',
-          explode: typeof parameter.explode === 'undefined' ? true : parameter.explode,
-          escape: parameter.allowReserved ? 'unsafe' : 'reserved',
-        }),
-        skipEncoding: true
-      }
+    req.query[parameter.name] = {
```
Comment (abcang) [inline src/execute/oas3/parameter-builders.js]: Since encoding is not required when sending using FormData, encoding has been changed to execute when executing mergeInQueryOrForm, as in the Open API v2.

File: src/http.js [hunk 2]
```diff
@@ -161,55 +162,145 @@ export function isFile(obj, navigatorObj) {
...
+    return true
   }
+  if (typeof Buffer !== 'undefined' && obj instanceof Buffer) {
+    return true
+  }
+
   return obj !== null && typeof obj === 'object' && typeof obj.pipe === 'function'
 }
 
-function formatValue(input, skipEncoding) {
```
Comment (abcang) [inline src/http.js]: Since the key may change depending on the value, `formatValue` has been changed to a method that returns a key-value pair

File: src/http.js [hunk 3]
```diff
@@ -161,55 +162,145 @@ export function isFile(obj, navigatorObj) {
...
+
+// Formats a key-value and returns an array of key-value pairs.
+//
+// Return value example 1: [['color', 'blue']]
+// Return value example 2: [['color', 'blue,black,brown']]
+// Return value example 3: [['color', ['blue', 'black', 'brown']]]
+// Return value example 4: [['color', 'R,100,G,200,B,150']]
+// Return value example 5: [['R', '100'], ['G', '200'], ['B', '150']]
+// Return value example 6: [['color[R]', '100'], ['color[G]', '200'], ['color[B]', '150']]
+function formatKeyValue(key, input, skipEncoding = false) {
```
Comment (abcang) [inline src/http.js]: Since the key may change depending on the value, `formatValue` has been changed to a method that returns a key-value pair

File: test/bugs/ui-4071.js [hunk 4]
```diff
@@ -35,7 +35,8 @@ const spec = {
               },
               encoding: {
                 industries: {
-                  style: 'form'
+                  style: 'form',
+                  explode: false
```
Comment (abcang) [inline test/bugs/ui-4071.js]: If style is `form`, the default value of explode is `true`. However, this test seemed to assume the behavior when explode was `false`, so I set explode to `false`.

File: test/bugs/ui-4071.js [hunk 5]
```diff
@@ -69,7 +70,7 @@ test(
       headers: {
         'Content-Type': 'application/x-www-form-urlencoded',
       },
-      body: 'industries=1%2C16'
+      body: 'industries=1,16'
```
Comment (abcang) [inline test/bugs/ui-4071.js]: Should `,` obey `allowReserved`?

Currently it follows the example table, regardless of `allowReserved`.
https://github.com/OAI/OpenAPI-Specification/blob/v3.1.0-dev/versions/3.1.0.md#encodingObject

File: test/oas3/execute/style-explode/query.js [hunk 6]
```diff
@@ -699,7 +699,7 @@ describe('OAS 3.0 - buildRequest w/ `style` & `explode` - query parameters', ()
 
         expect(req).toEqual({
           method: 'GET',
-          url: `/users?id=3 id=4 id=5 id=${SAFE_INPUT_RESULT}`,
+          url: `/users?id=3&id=4&id=5&id=${SAFE_INPUT_RESULT}`,
```
Comment (abcang) [inline test/oas3/execute/style-explode/query.js]: There is no example when style is spaceDelimited or pipeDelimited and explode is true, but the same behavior as when style is form is probably correct.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#style-examples

File: test/oas3/execute/style-explode/query.js [hunk 7]
```diff
@@ -781,7 +781,7 @@ describe('OAS 3.0 - buildRequest w/ `style` & `explode` - query parameters', ()
 
         expect(req).toEqual({
           method: 'GET',
-          url: `/users?id=3 4 5 ${SAFE_INPUT_RESULT}`,
+          url: `/users?id=3%204%205%20${SAFE_INPUT_RESULT}`,
```
Comment (abcang) [inline test/oas3/execute/style-explode/query.js]: According to the example table, when style is `spaceDelimited`, the value is delimited by `%20`.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#style-examples

File: test/oas3/execute/style-explode/query.js [hunk 8]
```diff
@@ -1327,7 +1327,7 @@ describe('OAS 3.0 - buildRequest w/ `style` & `explode` - query parameters', ()
 
         expect(req).toEqual({
           method: 'GET',
-          url: `/users?id[role]=admin&id[firstName]=Alex&id[greeting]=${SAFE_INPUT_RESULT}`,
+          url: `/users?id%5Brole%5D=admin&id%5BfirstName%5D=Alex&id%5Bgreeting%5D=${SAFE_INPUT_RESULT}`,
```
Comment (abcang) [inline test/oas3/execute/style-explode/query.js]: encodes `[` and `]` according to allowReserved

**Comment by tim-lai** [comment]
@abcang Thanks much for this PR. It looks well thought out. A related PR https://github.com/swagger-api/swagger-js/pull/1527  is inbound that should take care of the `multipart` case for both OAS2 and OAS3.0 while maintaining the existing `urlecoded` case. However, I am not sure if it directly address the title's `application/x-www-form-urlencoded` serialization case. If https://github.com/swagger-api/swagger-js/pull/1527 does not resolve your issue, please make any updates as needed, and I would be happy to take another look.

File: test/data/sample-multipart-oas3.js [hunk 9]
```diff
@@ -63,41 +69,41 @@ export default {
           }
         }
       },
-      '/land/content/uploadImage': {
```
Comment (abcang) [inline test/data/sample-multipart-oas3.js:66]: just fixed the indent

File: test/data/sample-multipart-oas3.js [hunk 10]
```diff
@@ -46,6 +46,12 @@ export default {
                     }
                   }
                 }
+              },
+              encoding: {
+                'email[]': {
+                  style: 'form',
```
Comment (abcang) [inline test/data/sample-multipart-oas3.js:52]: I have interpreted that if no Encoding Object is set, `explode` will not be enabled by default and the format will be based on the default value of contentType.

https://github.com/OAI/OpenAPI-Specification/blob/v3.1.0-dev/versions/3.1.0.md#encoding-object

So I thought I had to explicitly specify `explode`. (I personally felt that it would be more natural to treat it as `explode` by default ...)

**Comment by tim-lai** [comment]
@abcang Update:  Merged and released #1527 only ensured maintain of existing support of OAS3 x-www-form-urlencoded. After some additional QA, implementation of OAS3 x-www-form-urlencoded itself does need improvement. We should account for explode=true, explode=false, explode (default).

File: test/http-multipart.js [hunk 11]
```diff
@@ -188,4 +188,96 @@ describe('buildRequest - openapi 3.0', () => {
...
+        credentials: 'same-origin',
+        headers: {
+          'Content-Type': 'multipart/form-data'
+        },
+      })
+      const validateFormDataInstance = req.body instanceof FormData
+      expect(validateFormDataInstance).toEqual(true)
+      const itemEntries = req.body.getAll('images[]')
+      expect(itemEntries.length).toEqual(2)
+      expect(itemEntries[0].__content).toEqual(file1)
```
Comment (tim-lai) [inline test/http-multipart.js:262]:
```suggestion
      expect(itemEntries[0]).toEqual(file1)
```

Comment (tim-lai) [inline test/http-multipart.js:262]:
```suggestion
      expect(itemEntries[0]).toEqual(file1)
```

File: test/http-multipart.js [hunk 12]
```diff
@@ -188,4 +188,96 @@ describe('buildRequest - openapi 3.0', () => {
...
+      expect(req).toMatchObject({
+        method: 'POST',
+        url: 'http://petstore.swagger.io/v2/one',
+        credentials: 'same-origin',
+        headers: {
+          'Content-Type': 'multipart/form-data'
+        },
+      })
+
+      expect(Array.from(req.body.entries())).toEqual([['color[R]', '100'], ['color[G]', '200'], ['color[B]', '150']])
```
Comment (tim-lai) [inline test/http-multipart.js:324]:
```suggestion
      expect(Array.from(req.body.entries())).toEqual([{name: 'color[R]', value: '100'}, {name: 'color[G]', value: '200'}, {name: 'color[B]', value: '150'}])
```

**Comment by tim-lai** [comment]
@abcang Thanks for the update again! We need one more pass at this, due to the recent dependency reversion/patch of `form-data`. I've resolved the merge conflicts and requested changes to fix the tests that broke as a result.

File: test/http-multipart.js [hunk 13]
```diff
@@ -232,4 +232,96 @@ describe('buildRequest - openapi 3.0', () => {
...
+        headers: {
+          'Content-Type': 'multipart/form-data'
+        },
+      })
+      const validateFormDataInstance = req.body instanceof FormData
+      expect(validateFormDataInstance).toEqual(true)
+      const itemEntries = req.body.getAll('images[]')
+      expect(itemEntries.length).toEqual(2)
+      expect(itemEntries[0]).toEqual(file1)
+      expect(itemEntries[1].__content).toEqual(file2)
```
Comment (tim-lai) [inline test/http-multipart.js:263]:
```suggestion
      expect(itemEntries[1]).toEqual(file2)
```

File: test/http-multipart.js [hunk 14]
```diff
@@ -232,4 +232,96 @@ describe('buildRequest - openapi 3.0', () => {
...
+      expect(req).toMatchObject({
+        method: 'POST',
+        url: 'http://petstore.swagger.io/v2/one',
+        credentials: 'same-origin',
+        headers: {
+          'Content-Type': 'multipart/form-data'
+        },
+      })
+
+      expect(Array.from(req.body.entries())).toEqual([{name: 'color[R]', value: '100'}, {name: 'color[G]', value: '200'}, {name: 'color[B]', value: '150'}])
```
Comment (tim-lai) [inline test/http-multipart.js:324]:
```suggestion
      expect(Array.from(req.body._entryList)).toEqual([{name: 'color[R]', value: '100'}, {name: 'color[G]', value: '200'}, {name: 'color[B]', value: '150'}])
```

**Comment by abcang** [comment]
Thank you for reviewing and fixing the test!
